"""add iban

Revision ID: 4346ff4eb31e
Revises: 2da4cda258ae
Create Date: 2022-07-19 17:18:22.521653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4346ff4eb31e'
down_revision = '2da4cda258ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('iban', sa.String(length=22), nullable=False))
    op.add_column('approvers', sa.Column('iban', sa.String(length=22), nullable=False))
    op.add_column('complainers', sa.Column('iban', sa.String(length=22), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complainers', 'iban')
    op.drop_column('approvers', 'iban')
    op.drop_column('admins', 'iban')
    # ### end Alembic commands ###
